# site settings
title: M-N
subtitle: mindnous
email: brilian.eng@gmail.com
description: Combining GenAI; traditional AI; and Interactability on the edge<br /> "AI brings delight—keep the cost out of sight." - brilian
baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: Brilian Tafjira Nugraha
# street_address: 1234 Somewhere Road
city: Taipei
state: Taiwan
zip_code: 100
country: Taiwan (R.O.C)
phone: (886) 968-747-749

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/mindnous
  Google-Plus:
  LinkedIn: https://www.linkedin.com/in/brilian-tafjira-nugraha/
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
